# OpenRemote v3
#
# Profile for deploying the custom stack; uses deployment-data named volume
# to expose customisations to the manager and keycloak images. To run this profile you need to specify the following
# environment variables:
#
#    EMAIL - Admin email address
#    PASSWORD - Initial admin user password
#    DEPLOYMENT_HOST - Domain hostname of where this instance will be exposed (localhost or public domain)
#    DEPLOYMENT_VERSION - Tag to use for deployment image (must match the tag used when building the deployment image)
#    MANAGER_VERSION - Tag to use for manager image (must match the tag used when building the manager image)
#
# Please see profile/deploy.yml for configuration details for each service.
#
# To perform updates, build code and prepare Docker images:
#
#   ./gradlew clean installDist
#
# Then recreate deployment image:
#
#  DEPLOYMENT_VERSION=$(git rev-parse --short HEAD)
#  MANAGER_VERSION=$(cd openremote; git rev-parse --short HEAD; cd ..)
#  docker build -t openremote/manager:$MANAGER_VERSION ./openremote/manager/build/install/manager/
#  docker build -t openremote/custom-deployment:$DEPLOYMENT_VERSION ./deployment/build/
#  docker-compose -p custom down
#  docker volume rm custom_deployment-data
#  Do the following volume rm command if you want a clean install (wipe all existing data)
#  docker volume rm custom_postgresql-data
#  PASSWORD=secret DEPLOYMENT_HOST=my.domain.com docker-compose -p custom up -d
#
# All data is kept in volumes. Create a backup of the volumes to preserve data.
#
version: '2.4'

volumes:
  proxy-data:
  deployment-data:
  postgresql-data:
  temp-data:

services:

  # This service will only populate an empty volume on startup and then exit.
  # If the volume already contains data, it exits immediately.
  deployment:
    image: openremote/deployment:${DEPLOYMENT_VERSION?DEPLOYMENT_VERSION must be set}
    volumes:
      - deployment-data:/deployment

  proxy:
    image: openremote/proxy:latest${PROXY_VERSION:-2.5.0.1}
    restart: always
    depends_on:
      manager:
        condition: service_healthy
    ports:
      - "80:80"
      - "443:443"
      - "8883:8883"
    volumes:
      - proxy-data:/deployment
      - deployment-data:/data
    environment:
      LE_EMAIL: ${SETUP_EMAIL_TO?SETUP_EMAIL_TO must be set}
      DOMAINNAME: ${HOST?HOST must be set}
      # USE A CUSTOM PROXY CONFIG - COPY FROM https://github.com/openremote/proxy/blob/main/haproxy.cfg
      #HAPROXY_CONFIG: '/data/proxy/haproxy.cfg'

  postgresql:
    image: openremote/postgresql:${POSTGRESQL_VERSION:-14.1.0.0}
    restart: always
    volumes:
      - postgresql-data:/var/lib/postgresql/data
      - temp-data:/tmp

  keycloak:
    image: openremote/keycloak:${KEYCLOAK_VERSION:-16.0.0.0}
    restart: always
    depends_on:
      postgresql:
        condition: service_healthy
    volumes:
      - deployment-data:/deployment
    environment:
      KEYCLOAK_PASSWORD: ${SETUP_ADMIN_PASSWORD:?SETUP_ADMIN_PASSWORD must be set}
      KEYCLOAK_FRONTEND_URL: https://${HOST?HOST must be set}/auth

  manager:
    image: openremote/manager:${MANAGER_VERSION?MANAGER_VERSION must be set}
    restart: always
    logging:
      options:
        max-size: "10m"
        max-file: "10"
    depends_on:
      keycloak:
        condition: service_healthy
    volumes:
      - temp-data:/tmp
      - deployment-data:/deployment
      # Map data is stored local on host
      - /deployment.local:/deployment.local
    environment:
      # Here are some typical environment variables you want to set
      # see openremote/profile/deploy.yml for details
      SETUP_ADMIN_PASSWORD: ${SETUP_ADMIN_PASSWORD?SETUP_ADMIN_PASSWORD must be set}
      SETUP_TYPE: # Typical values to support are staging and production
      SETUP_EMAIL_HOST:
      SETUP_EMAIL_PORT:
      SETUP_EMAIL_USER:
      SETUP_EMAIL_PASSWORD:
      SETUP_EMAIL_FROM:
      SETUP_EMAIL_TO:
      #MAP_TILES_PATH: '/deployment.local/map/mapdata.mbtiles'
